[build]
  command = "npm run build"  # Adjust if you have a build step
  publish = "dist"           # The directory where your static files are located (if any)

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
